global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'todoLists'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['todo-list:8080']