{
 "title": "Todo list app",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_gc_memory_allocated_bytes_total, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_gc_memory_allocated_bytes_total{application=~\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=~\"$application\", instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=~\"$application\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP status: 2xx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", status=~\"2..\"} or vector(0))"
    }
   ]
  },
  {
   "title": "HTTP status: 3xx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", status=~\"3..\"} or vector(0))"
    }
   ]
  },
  {
   "title": "HTTP status: 4xx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", status=~\"4..\"} or vector(0))"
    }
   ]
  },
  {
   "title": "HTTP status: 5xx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$application\", instance=~\"$instance\", status=~\"5..\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Warn logs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(logback_events_total{application=~\"$application\", instance=~\"$instance\", level=\"warn\"} or vector(0))"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(logback_events_total{application=~\"$application\", instance=~\"$instance\", level=\"error\"} or vector(0))"
    }
   ]
  },
  { "title": "HTTP traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Response times [0.90]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds{application=~\"$application\",instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "{{ method }} {{ uri }} {{status}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=~\"$application\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ method }} {{ uri }} {{status}}"
    }
   ]
  }
 ]
}