todo-lists:
  limit: 5

security:
  jwe-token:
    secret: 8gtpDtBl6cwsDBDLoWu/0A==

spring:
  application:
    name: todo-app
  data:
    mongodb:
      uri: mongodb://localhost/todoList

springdoc:
  swagger-ui:
    path: /swagger-ui.html
